version: "3.9"
services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: PhoneCatalogAPI
      dockerfile: ./PhoneCatalogAPI/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - database:/app/Database
volumes:
  database: